# Generated by Django 4.2.1 on 2024-04-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickuplocation', models.CharField(max_length=30)),
                ('pickupdate', models.CharField(max_length=30)),
                ('pickuptime', models.CharField(max_length=30)),
                ('dropofflocation', models.CharField(max_length=30)),
                ('dropoffdate', models.CharField(max_length=30)),
                ('dropofftime', models.CharField(max_length=30)),
                ('vehicletype', models.CharField(max_length=30)),
                ('drivinglicence', models.CharField(max_length=30)),
                ('persnolinformation', models.CharField(max_length=30)),
            ],
        ),
    ]
