# Generated by Django 4.2.1 on 2024-04-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_carrental'),
    ]

    operations = [
        migrations.CreateModel(
            name='mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('work_duration', models.CharField(default='', max_length=30)),
                ('salary', models.CharField(max_length=30)),
            ],
        ),
    ]
