# Generated by Django 4.2.1 on 2024-04-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_mechanic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrental',
            name='drivinglicence',
        ),
        migrations.RemoveField(
            model_name='carrental',
            name='persnolinformation',
        ),
        migrations.RemoveField(
            model_name='carrental',
            name='vehicletype',
        ),
    ]
